FROM eclipse-temurin:17-jdk-alpine
 
WORKDIR /app

COPY mvnw .
COPY .mvn .mvn
RUN chmod +x mvnw

# Copy pom.xml and download dependencies
COPY pom.xml .
RUN ./mvnw dependency:go-offline -B

# Copy source code
COPY src ./src

RUN ./mvnw clean package -DskipTests

EXPOSE 8080 5005

# Run with hot reload (spring-boot-devtools)
CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"]
