FROM mcr.microsoft.com/devcontainers/java:1-17-bullseye

# Install additional OS packages if needed
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# Set the working directory
WORKDIR /app

# Expose ports
EXPOSE 8080 5005
